('IDENTIFIER', 'table1')
('WHITESPACE', ' ')
('EQ', '=')
('WHITESPACE', ' ')
('LOAD', 'LOAD')
('WHITESPACE', ' ')
('STRING', 'class_roster.csv')
('SHOW', 'SHOW')
('WHITESPACE', ' ')
('ROWS', 'ROWS')
('WHITESPACE', ' ')
('IDENTIFIER', 'table1')
('SHOW', 'SHOW')
('WHITESPACE', ' ')
('COLUMNS', 'COLUMNS')
('WHITESPACE', ' ')
('IDENTIFIER', 'table1')
('IDENTIFIER', 'sub_table')
('WHITESPACE', ' ')
('EQ', '=')
('WHITESPACE', ' ')
('GET', 'GET')
('WHITESPACE', ' ')
('LPAREN', '(')
('IDENTIFIER', 'NAME')
('COMMA', ',')
('WHITESPACE', ' ')
('IDENTIFIER', 'AGE')
('COMMA', ',')
('WHITESPACE', ' ')
('IDENTIFIER', 'YEAR')
('RPAREN', ')')
('WHITESPACE', ' ')
('FROM', 'FROM')
('WHITESPACE', ' ')
('IDENTIFIER', 'table1')
('IDENTIFIER', 'chart1')
('WHITESPACE', ' ')
('EQ', '=')
('WHITESPACE', ' ')
('CONVERT', 'CONVERT')
('WHITESPACE', ' ')
('IDENTIFIER', 'group_table')
('WHITESPACE', ' ')
('TO', 'TO')
('WHITESPACE', ' ')
('BARCHART', 'BARCHART')
('OUTPUT', 'OUTPUT')
('WHITESPACE', ' ')
('IDENTIFIER', 'group_table')
('WHITESPACE', ' ')
('TO', 'TO')
('WHITESPACE', ' ')
('STRING', 'group_table_file')
('WHITESPACE', ' ')
('AS', 'AS')
('WHITESPACE', ' ')
('CSV', 'CSV')
('OUTPUT', 'OUTPUT')
('WHITESPACE', ' ')
('IDENTIFIER', 'group_table')
('WHITESPACE', ' ')
('TO', 'TO')
('WHITESPACE', ' ')
('STRING', 'group_table_file')
('WHITESPACE', ' ')
('AS', 'AS')
('WHITESPACE', ' ')
('PDF', 'PDF')
('OUTPUT', 'OUTPUT')
('WHITESPACE', ' ')
('IDENTIFIER', 'group_table')
('WHITESPACE', ' ')
('TO', 'TO')
('WHITESPACE', ' ')
('STRING', 'chart1')
('WHITESPACE', ' ')
('AS', 'AS')
('WHITESPACE', ' ')
('JPEG', 'JPEG')
